version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell

formatters:
  enable:
    - gofmt

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
