version: 2

project_name: vivecaka

before:
  hooks:
    - go mod tidy

builds:
  - id: vivecaka
    main: ./cmd/vivecaka
    binary: vivecaka
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: "^feat"
    - title: Fixes
      regexp: "^fix"
    - title: Others
      order: 999

release:
  github:
    owner: indrasvat
    name: vivecaka
